[[quote]]
text = "I am not afraid of dying; I am prepared for it, but I still do not like it."
author = "Queen Victoria"

[[quote]]
text = "I am ready to meet my Maker. Whether my Maker is prepared for the great ordeal of meeting me is another matter."
author = "Winston Churchill"

[[quote]]
text = "I have lived and now must die. Life is duty, death a necessity."
author = "Lord Melbourne"

[[quote]]
text = "Courage is resistance to fear, mastery of fear, not absence of fear."
author = "Mark Twain"

[[quote]]
text = "Death is a delightful hiding place for weary men."
author = "Herodotus"

[[quote]]
text = "It is not death that a man should fear, but he should fear never beginning to live."
author = "Marcus Aurelius"

[[quote]]
text = "A man’s dying is more the survivors’ affair than his own."
author = "Thomas Mann"

[[quote]]
text = "Cowards die many times before their deaths; the valiant never taste of death but once."
author = "William Shakespeare"

[[quote]]
text = "To die will be an awfully big adventure."
author = "J.M. Barrie"

[[quote]]
text = "Death may be the greatest of all human blessings."
author = "Socrates"

[[quote]]
text = "He who fears death will never do anything worth of a man who is alive."
author = "Seneca"

[[quote]]
text = "While I thought that I was learning how to live, I have been learning how to die."
author = "Leonardo da Vinci"

[[quote]]
text = "The idea is to die young as late as possible."
author = "Ashley Montagu"

[[quote]]
text = "Death is the end of a lifetime, not the end of a relationship."
author = "Mitch Albom"

[[quote]]
text = "Death is nature’s way of telling you to slow down."
author = "Dick Sharples"

[[quote]]
text = "Death is nothing, but to live defeated and inglorious is to die daily."
author = "Napoleon Bonaparte"

[[quote]]
text = "Our dead are never dead to us, until we have forgotten them."
author = "George Eliot"

[[quote]]
text = "It is not length of life, but depth of life."
author = "Ralph Waldo Emerson"

[[quote]]
text = "The only certainty in life is death."
author = "G. K. Chesterton"

[[quote]]
text = "The long habit of living indisposeth us for dying."
author = "Sir Thomas Browne"

[[quote]]
text = "All men think all men mortal but themselves."
author = "Edward Young"

[[quote]]
text = "Death is not extinguishing the light; it is only putting out the lamp because the dawn has come."
author = "Rabindranath Tagore"

[[quote]]
text = "Death is the sound of distant thunder at a picnic."
author = "W. H. Auden"

[[quote]]
text = "For death is no more than a turning of us over from time to eternity."
author = "William Penn"

[[quote]]
text = "Death is the destination we all share. No one has ever escaped it."
author = "Steve Jobs"

[[quote]]
text = "Our life dreams the Utopia. Our death achieves the Ideal."
author = "Victor Hugo"

[[quote]]
text = "Every man must do two things alone; he must do his own believing and his own dying."
author = "Martin Luther"

[[quote]]
text = "To fear death, my friends, is only to think ourselves wise without being wise."
author = "Socrates"

[[quote]]
text = "The life of the dead is placed in the memory of the living."
author = "Marcus Tullius Cicero"

[[quote]]
text = "Do not fear death so much but rather the inadequate life."
author = "Bertolt Brecht"

[[quote]]
text = "Death is more universal than life; everyone dies but not everyone lives."
author = "Andrew Sachs"

[[quote]]
text = "The fear of death is the most unjustified of all fears, for there's no risk of accident for someone who's dead."
author = "Albert Einstein"

[[quote]]
text = "The goal of all life is death."
author = "Sigmund Freud"

[[quote]]
text = "Life and death are one thread, the same line viewed from different sides."
author = "Lao Tzu"

[[quote]]
text = "After your death, you will be what you were before your birth."
author = "Arthur Schopenhauer"

[[quote]]
text = "Death is the veil which those who live call life; they sleep, and it is lifted."
author = "Percy Bysshe Shelley"

[[quote]]
text = "Life is short, death is forever."
author = "Chuck Palahniuk"

[[quote]]
text = "The fear of death follows from the fear of life. A man who lives fully is prepared to die at any time."
author = "Mark Twain"

[[quote]]
text = "Death is the final wake-up call."
author = "Doug Horton"

[[quote]]
text = "We're all going to die. We're all going to have to live through it."
author = "Ray Bradbury"

[[quote]]
text = "Death is not the opposite of life, but a part of it."
author = "Haruki Murakami"

[[quote]]
text = "The truth I have been seeking — this truth is death. Yet death is also a seeker. Forever seeking me."
author = "Octavio Paz"

[[quote]]
text = "In the end, it's not the years in your life that count, it's the life in your years."
author = "Abraham Lincoln"

[[quote]]
text = "We all die. The goal isn't to live forever, the goal is to create something that will."
author = "Chuck Palahniuk"

[[quote]]
text = "Death ends a life, not a relationship."
author = "Mitch Albom"

[[quote]]
text = "Life is uncertain; death is certain."
author = "Buddha"

[[quote]]
text = "Death is the great equalizer."
author = "Anonymous"

[[quote]]
text = "Death never takes the wise man by surprise, he is always ready to go."
author = "Jean de La Fontaine"

[[quote]]
text = "We understand death for the first time when he puts his hand upon one whom we love."
author = "Madame de Stael"

[[quote]]
text = "To live in hearts we leave behind is not to die."
author = "Thomas Campbell"

[[quote]]
text = "Life is a dream for the wise, a game for the fool, a comedy for the rich, a tragedy for the poor."
author = "Sholom Aleichem"

[[quote]]
text = "Death is the wish of some, the relief of many, and the end of all."
author = "Seneca"

[[quote]]
text = "Good men must die, but death cannot kill their names."
author = "Proverb"

[[quote]]
text = "While we are mourning the loss of our friend, others are rejoicing to meet him behind the veil."
author = "John Taylor"

[[quote]]
text = "When someone you love becomes a memory, the memory becomes a treasure."
author = "Anonymous"

[[quote]]
text = "Death is not the greatest loss in life. The greatest loss is what dies inside us while we live."
author = "Norman Cousins"

[[quote]]
text = "To die is poignantly bitter, but the idea of having to die without having lived is unbearable."
author = "Erich Fromm"

[[quote]]
text = "People living deeply have no fear of death."
author = "Anaïs Nin"

[[quote]]
text = "Life is a great sunrise. I do not see why death should not be an even greater one."
author = "Vladimir Nabokov"

[[quote]]
text = "Death is a challenge. It tells us not to waste time. It tells us to tell each other right now that we love each other."
author = "Leo Buscaglia"

[[quote]]
text = "Death is no more than passing from one room into another. But there's a difference for me, you know. Because in that other room I shall be able to see."
author = "Helen Keller"

[[quote]]
text = "If life must not be taken too seriously, then so neither must death."
author = "Samuel Butler"

[[quote]]
text = "Death is nothing else but going home to God, the bond of love will be unbroken for all eternity."
author = "Mother Teresa"

[[quote]]
text = "You can’t truly heal from a loss until you allow yourself to really FEEL the loss."
author = "Mandy Hale"

[[quote]]
text = "Death is a natural part of life. Rejoice for those around you who transform into the Force."
author = "Yoda"

[[quote]]
text = "When your time comes to die, be not like those whose hearts are filled with the fear of death, so that when their time comes they weep and pray for a little more time to live their lives over again in a different way. Sing your death song, and die like a hero going home."
author = "Tecumseh"

[[quote]]
text = "Even death is not to be feared by one who has lived wisely."
author = "Buddha"

[[quote]]
text = "The world is afflicted by death and decay. But the wise do not grieve, having realized the nature of the world."
author = "Buddha"

[[quote]]
text = "This existence of ours is as transient as autumn clouds. To watch the birth and death of beings is like looking at the movements of a dance."
author = "Buddha"

[[quote]]
text = "Long is the cycle of birth and death to the fool who does not know the true path."
author = "Buddha"

[[quote]]
text = "Ardently do today what must be done. Who knows? Tomorrow, death comes."
author = "Buddha"

[[quote]]
text = "The end of birth is death; the end of death is birth. This is the holy law."
author = "Buddha"

[[quote]]
text = "Everything is changeable, everything appears and disappears; there is no blissful peace until one passes beyond the agony of life and death."
author = "Buddha"

[[quote]]
text = "Just as a mother would protect her only child with her life, even so let one cultivate a boundless love towards all beings."
author = "Buddha"

[[quote]]
text = "Health is the greatest gift, contentment the greatest wealth, faithfulness the best relationship."
author = "Buddha"

[[quote]]
text = "In the end, these things matter most: How well did you love? How fully did you live? How deeply did you let go?"
author = "Buddha"

[[quote]]
text = "Death carries off a man busy picking flowers with an besotted mind, like a great flood does a sleeping village."
author = "Buddha"

[[quote]]
text = "Not in the sky, nor in the middle of the sea, nor entering an opening in the mountains is there that place on earth where standing one might be freed from evil action."
author = "Buddha"

[[quote]]
text = "The secret of health for both mind and body is not to mourn for the past, nor to worry about the future, but to live the present moment wisely and earnestly."
author = "Buddha"

[[quote]]
text = "With mindfulness, strive on."
author = "Buddha"

[[quote]]
text = "All conditioned things are impermanent. Work out your own salvation with diligence."
author = "Buddha"

[[quote]]
text = "To be idle is a short road to death and to be diligent is a way of life; foolish people are idle, wise people are diligent."
author = "Buddha"

[[quote]]
text = "Delight in heedfulness! Guard well your thoughts!"
author = "Buddha"

[[quote]]
text = "No one saves us but ourselves. No one can and no one may. We ourselves must walk the path."
author = "Buddha"

[[quote]]
text = "Your work is to discover your work and then with all your heart to give yourself to it."
author = "Buddha"

[[quote]]
text = "Do not be afraid of death. Be afraid of the half-lived life."
author = "Lajos Kassák"

[[quote]]
text = "To live in the hearts we leave behind is not to die."
author = "Tupac Shakur"

[[quote]]
text = "Life is a process of becoming, a combination of states we have to go through. Where people fail is that they wish to elect a state and remain in it. This is a kind of death."
author = "Anaïs Nin"

[[quote]]
text = "Death is the golden key that opens the palace of eternity."
author = "John Milton"

[[quote]]
text = "There is no cure for birth and death save to enjoy the interval."
author = "George Santayana"

[[quote]]
text = "The boundaries which divide life from death are at best shadowy and vague. Who shall say where the one ends, and where the other begins?"
author = "Edgar Allan Poe"

[[quote]]
text = "Death is the dropping of the flower that the fruit may swell."
author = "Henry Ward Beecher"

[[quote]]
text = "You matter because you are you, and you matter until the last moment of your life."
author = "Cicely Saunders"

[[quote]]
text = "The fear of death is the beginning of slavery."
author = "Robert Anton Wilson"

[[quote]]
text = "To fear love is to fear life, and those who fear life are already three parts dead."
author = "Bertrand Russell"

[[quote]]
text = "For life and death are one, even as the river and the sea are one."
author = "Khalil Gibran"

[[quote]]
text = "Life is like a coin. You can spend it any way you wish, but you only spend it once."
author = "Lillian Dickson"

[[quote]]
text = "Our life is composed of two parts, the past and the future; the former is gone, the latter does not yet appear. The present is but a point."
author = "Jean de La Bruyère"

[[quote]]
text = "Your body is away from me, but there is a window open from my heart to yours."
author = "Rumi"

[[quote]]
text = "We are not human beings having a spiritual experience. We are spiritual beings having a human experience."
author = "Pierre Teilhard de Chardin"

[[quote]]
text = "Life is a journey that must be traveled no matter how bad the roads and accommodations."
author = "Oliver Goldsmith"

[[quote]]
text = "When I die, I will soar with angels, and when I die to the angels, what I shall become you cannot imagine."
author = "Rumi"